# Generated by Django 2.2 on 2021-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_catitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='catitems',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
